#!/usr/bin/env bash
# Displays information about subdomains

display_info() {
    local domain=$1
    local subdomain=$2
    host -t A "${subdomain}.${domain}" | awk '/has address/ {
        print "The subdomain " $1 " is a A record and points to " $4
    }' | sed "s/.${domain}//g"
}

domain=$1
subdomain=$2

if [ "$#" -lt 1 ]; then
    echo "Usage: 0-world_wide_web <domain> [subdomain]"
    exit 1
fi

if [ -z "$subdomain" ]; then
    display_info "$domain" "web-01"
    display_info "$domain" "web-02"
    display_info "$domain" "lb-01"
    display_info "$domain" "web-01"
else
    display_info "$domain" "$subdomain"
fi