#!/usr/bin/env bash
# Displays information about subdomains

display_info() {
    local domain=$1
    local subdomain=$2
    local result
    result=$(dig +short "$subdomain.$domain" A)
    if [ -n "$result" ]; then
        echo "The subdomain $subdomain is a A record and points to $result"
    fi
}

domain=$1
subdomain=$2

if [ "$#" -lt 1 ]; then
    echo "Usage: 0-world_wide_web <domain> [subdomain]"
    exit 1
fi

if [ -z "$subdomain" ]; then
    display_info "$domain" "www"
    display_info "$domain" "lb-01"
    display_info "$domain" "web-01"
    display_info "$domain" "web-02"
else
    display_info "$domain" "$subdomain"
fi